# for local development
version: '3.7'
services:
  gridsome:
    build:
      context: .
      target: 'develop-stage'
    ports:
      - '8080:8080'
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: /bin/sh -c "yarn develop"
